
name: train-model

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
#    - name: Get python version
      run: pip install -r requirements.txt
#      run: python -V
    - name: Train model
      run: python train.py
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: random_forest_classifier.pkl
        path: random_forest_classifier.pkl